/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Main": import("@cloudflare/workers-types").Service
    "VisitorsStore": import("@cloudflare/workers-types").KVNamespace
  }
}

import "sst"
export {}